int putchar(int);

void condition_if(int a) {
	if (a) {putchar('E'); putchar('n'); putchar('t'); putchar('e'); putchar('r'); putchar('e'); putchar('d'); putchar(' '); putchar('i'); putchar('f'); putchar('\n');}
	else {putchar('E'); putchar('n'); putchar('t'); putchar('e'); putchar('r'); putchar('e'); putchar('d'); putchar(' '); putchar('e'); putchar('l'); putchar('s'); putchar('e'); putchar('\n');}	
}

void condition_while(int a, int b) {
	a = a;
	while (a <= b) {
		putchar(a);
		a = a + 1;
	}
	putchar('\n');
}

void comma_expressions(int a) {
	putchar((a = a + 1, a = a + 2, 3) + '0');
}

char call(int a, short b, char c, double d) {
	a >= 9 || (b = call(a + 1, a, c, d));
	putchar('0' + a);
	putchar('0' + b);
	putchar('\n');
	return b;
}

int a = 1;
short b = 2;
char c = 3;
int d = 4;
// 20 pontos
int main(void){
	condition_if(0);
	condition_if(1);
	condition_while('0', '9');
	condition_while('a', 'z');
	condition_while('A', 'Z');
	comma_expressions(0);
	// putchar(call(1, 2, 3, 3) + '0');
	// putchar('\n');


// 	return 0;
// }

// int main(void){
	putchar((a+ a) + '0');
	putchar((a+ b) + '0');
	putchar((a+ c) + '0');
	putchar((a+ d) + '0');
	putchar((b+ b) + '0');
	putchar((b+ c) + '0');
	putchar((b+ d) + '0');
	putchar((c+ c) + '0');
	putchar((c+ d) + '0');
	putchar((d+ d) + '0');
	putchar((a+ a) + '0');
	putchar((b+ a) + '0');
	putchar((c+ a) + '0');
	putchar((d+ a) + '0');
	putchar((b+ b) + '0');
	putchar((c+ b) + '0');
	putchar((d+ b) + '0');
	putchar((c+ c) + '0');
	putchar((a- a) + '0');
	putchar((a- b) + '0');
	putchar((a- c) + '0');
	putchar((a- d) + '0');
	putchar((b- b) + '0');
	putchar((b- c) + '0');
	putchar((b- d) + '0');
	putchar((c- c) + '0');
	putchar((c- d) + '0');
	putchar((d- d) + '0');
	putchar((a- a) + '0');
	putchar((b- a) + '0');
	putchar((c- a) + '0');
	putchar((d- a) + '0');
	putchar((b- b) + '0');
	putchar((c- b) + '0');
	putchar((d- b) + '0');
	putchar((c- c) + '0');
	putchar((a* a) + '0');
	putchar((a* b) + '0');
	putchar((a* c) + '0');
	putchar((a* d) + '0');
	putchar((b* b) + '0');
	putchar((b* c) + '0');
	putchar((b* d) + '0');
	putchar((c* c) + '0');
	putchar((c* d) + '0');
	putchar((d* d) + '0');
	putchar((a* a) + '0');
	putchar((b* a) + '0');
	putchar((c* a) + '0');
	putchar((d* a) + '0');
	putchar((b* b) + '0');
	putchar((c* b) + '0');
	putchar((d* b) + '0');
	putchar((c* c) + '0');
	putchar((a/ a) + '0');
	putchar((a/ b) + '0');
	putchar((a/ c) + '0');
	putchar((a/ d) + '0');
	putchar((b/ b) + '0');
	putchar((b/ c) + '0');
	putchar((b/ d) + '0');
	putchar((c/ c) + '0');
	putchar((c/ d) + '0');
	putchar((d/ d) + '0');
	putchar((a/ a) + '0');
	putchar((b/ a) + '0');
	putchar((c/ a) + '0');
	putchar((d/ a) + '0');
	putchar((b/ b) + '0');
	putchar((c/ b) + '0');
	putchar((d/ b) + '0');
	putchar((c/ c) + '0');
	putchar((a% a) + '0');
	putchar((a% b) + '0');
	putchar((a% c) + '0');
	putchar((b% b) + '0');
	putchar((b% c) + '0');
	putchar((c% c) + '0');
	putchar((a% a) + '0');
	putchar((b% a) + '0');
	putchar((c% a) + '0');
	putchar((b% b) + '0');
	putchar((c% b) + '0');
	putchar((c% c) + '0');
	putchar((a& a) + '0');
	putchar((a& b) + '0');
	putchar((a& c) + '0');
	putchar((b& b) + '0');
	putchar((b& c) + '0');
	putchar((c& c) + '0');
	putchar((a& a) + '0');
	putchar((b& a) + '0');
	putchar((c& a) + '0');
	putchar((b& b) + '0');
	putchar((c& b) + '0');
	putchar((c& c) + '0');
	putchar((a| a) + '0');
	putchar((a| b) + '0');
	putchar((a| c) + '0');
	putchar((b| b) + '0');
	putchar((b| c) + '0');
	putchar((c| c) + '0');
	putchar((a| a) + '0');
	putchar((b| a) + '0');
	putchar((c| a) + '0');
	putchar((b| b) + '0');
	putchar((c| b) + '0');
	putchar((c| c) + '0');
	putchar((a^ a) + '0');
	putchar((a^ b) + '0');
	putchar((a^ c) + '0');
	putchar((b^ b) + '0');
	putchar((b^ c) + '0');
	putchar((c^ c) + '0');
	putchar((a^ a) + '0');
	putchar((b^ a) + '0');
	putchar((c^ a) + '0');
	putchar((b^ b) + '0');
	putchar((c^ b) + '0');
	putchar((c^ c) + '0');
	putchar((a< a) + '0');
	putchar((a< b) + '0');
	putchar((a< c) + '0');
	putchar((a< d) + '0');
	putchar((b< b) + '0');
	putchar((b< c) + '0');
	putchar((b< d) + '0');
	putchar((c< c) + '0');
	putchar((c< d) + '0');
	putchar((d< d) + '0');
	putchar((a< a) + '0');
	putchar((b< a) + '0');
	putchar((c< a) + '0');
	putchar((d< a) + '0');
	putchar((b< b) + '0');
	putchar((c< b) + '0');
	putchar((d< b) + '0');
	putchar((c< c) + '0');
	putchar((a> a) + '0');
	putchar((a> b) + '0');
	putchar((a> c) + '0');
	putchar((a> d) + '0');
	putchar((b> b) + '0');
	putchar((b> c) + '0');
	putchar((b> d) + '0');
	putchar((c> c) + '0');
	putchar((c> d) + '0');
	putchar((d> d) + '0');
	putchar((a> a) + '0');
	putchar((b> a) + '0');
	putchar((c> a) + '0');
	putchar((d> a) + '0');
	putchar((b> b) + '0');
	putchar((c> b) + '0');
	putchar((d> b) + '0');
	putchar((c> c) + '0');
	putchar((a<=a) + '0');
	putchar((a<=b) + '0');
	putchar((a<=c) + '0');
	putchar((a<=d) + '0');
	putchar((b<=b) + '0');
	putchar((b<=c) + '0');
	putchar((b<=d) + '0');
	putchar((c<=c) + '0');
	putchar((c<=d) + '0');
	putchar((d<=d) + '0');
	putchar((a<=a) + '0');
	putchar((b<=a) + '0');
	putchar((c<=a) + '0');
	putchar((d<=a) + '0');
	putchar((b<=b) + '0');
	putchar((c<=b) + '0');
	putchar((d<=b) + '0');
	putchar((c<=c) + '0');
	putchar((a>=a) + '0');
	putchar((a>=b) + '0');
	putchar((a>=c) + '0');
	putchar((a>=d) + '0');
	putchar((b>=b) + '0');
	putchar((b>=c) + '0');
	putchar((b>=d) + '0');
	putchar((c>=c) + '0');
	putchar((c>=d) + '0');
	putchar((d>=d) + '0');
	putchar((a>=a) + '0');
	putchar((b>=a) + '0');
	putchar((c>=a) + '0');
	putchar((d>=a) + '0');
	putchar((b>=b) + '0');
	putchar((c>=b) + '0');
	putchar((d>=b) + '0');
	putchar((c>=c) + '0');
	putchar((a!=a) + '0');
	putchar((a!=b) + '0');
	putchar((a!=c) + '0');
	putchar((a!=d) + '0');
	putchar((b!=b) + '0');
	putchar((b!=c) + '0');
	putchar((b!=d) + '0');
	putchar((c!=c) + '0');
	putchar((c!=d) + '0');
	putchar((d!=d) + '0');
	putchar((a!=a) + '0');
	putchar((b!=a) + '0');
	putchar((c!=a) + '0');
	putchar((d!=a) + '0');
	putchar((b!=b) + '0');
	putchar((c!=b) + '0');
	putchar((d!=b) + '0');
	putchar((c!=c) + '0');
	putchar((a==a) + '0');
	putchar((a==b) + '0');
	putchar((a==c) + '0');
	putchar((a==d) + '0');
	putchar((b==b) + '0');
	putchar((b==c) + '0');
	putchar((b==d) + '0');
	putchar((c==c) + '0');
	putchar((c==d) + '0');
	putchar((d==d) + '0');
	putchar((a==a) + '0');
	putchar((b==a) + '0');
	putchar((c==a) + '0');
	putchar((d==a) + '0');
	putchar((b==b) + '0');
	putchar((c==b) + '0');
	putchar((d==b) + '0');
	putchar((c==c) + '0');
	putchar((a&&a) + '0');
	putchar((a&&b) + '0');
	putchar((a&&c) + '0');
	putchar((a&&d) + '0');
	putchar((b&&b) + '0');
	putchar((b&&c) + '0');
	putchar((b&&d) + '0');
	putchar((c&&c) + '0');
	putchar((c&&d) + '0');
	putchar((d&&d) + '0');
	putchar((a&&a) + '0');
	putchar((b&&a) + '0');
	putchar((c&&a) + '0');
	putchar((d&&a) + '0');
	putchar((b&&b) + '0');
	putchar((c&&b) + '0');
	putchar((d&&b) + '0');
	putchar((c&&c) + '0');
	putchar((a||a) + '0');
	putchar((a||b) + '0');
	putchar((a||c) + '0');
	putchar((a||d) + '0');
	putchar((b||b) + '0');
	putchar((b||c) + '0');
	putchar((b||d) + '0');
	putchar((c||c) + '0');
	putchar((c||d) + '0');
	putchar((d||d) + '0');
	putchar((a||a) + '0');
	putchar((b||a) + '0');
	putchar((c||a) + '0');
	putchar((d||a) + '0');
	putchar((b||b) + '0');
	putchar((c||b) + '0');
	putchar((d||b) + '0');
	putchar((c||c) + '0');
	return 0;
}